// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
)

type User struct {
	ID           []byte
	Email        string
	Password     string
	Registeredat sql.NullTime
	Verfied      bool
}
